"""Crawler for the BOE *Códigos Electrónicos* relevant to autonomic taxation.

The BOE maintains consolidated electronic codes that bundle the
state-level tax laws together with the regulatory measures of each
autonomous community. They are the cleanest, most stable source of
consolidated autonomic tax law because:

- The PDF is regenerated by the BOE every time a relevant amendment is
  published, so the consolidation is always current.
- The URL pattern is uniform across CCAA, making maintenance trivial.
- All 15 régimen común autonomies are covered (foral regimes — País
  Vasco and Navarra — are excluded by design; they require a separate
  ingestion path against their own boletines).

The catalogue below curates the codes that actually matter for the
three tributos with autonomic competence:

- ISD (Sucesiones y Donaciones)
- ITP / AJD (Transmisiones Patrimoniales y Actos Jurídicos Documentados)
- IRPF tramo autonómico (incluido en cada Código autonómico)
"""

from __future__ import annotations

from collections.abc import Generator
from datetime import UTC, datetime
import json
import os
import re
from typing import Any

import scrapy
from scrapy.http import Response

BOE_BASE_URL = "https://www.boe.es/biblioteca_juridica/codigos"


CCAA_REGIMEN_COMUN: dict[str, str] = {
    "andalucia": "AN",
    "aragon": "AR",
    "asturias": "AS",
    "baleares": "IB",
    "canarias": "CN",
    "cantabria": "CB",
    "castilla_la_mancha": "CM",
    "castilla_y_leon": "CL",
    "cataluna": "CT",
    "comunidad_valenciana": "VC",
    "extremadura": "EX",
    "galicia": "GA",
    "madrid": "MD",
    "murcia": "MC",
    "la_rioja": "RI",
}


# Curated list of BOE consolidated codes that actually cover autonomic
# fiscal regulation. The filename is the stem used by the BOE PDF endpoint.
# Verified codes have ``known=True``; the rest are best-effort defaults
# kept as fallback so a single missing PDF does not abort the whole crawl.
DEFAULT_CCAA_CODES: dict[str, dict[str, Any]] = {
    "andalucia": {"code_id": "229", "filename": "229_Codigo_de_Andalucia", "known": True},
    "aragon": {"code_id": "231", "filename": "231_Codigo_de_Aragon", "known": False},
    "asturias": {"code_id": "233", "filename": "233_Codigo_del_Principado_de_Asturias", "known": False},
    "baleares": {"code_id": "234", "filename": "234_Codigo_de_las_Illes_Balears", "known": False},
    "canarias": {"code_id": "235", "filename": "235_Codigo_de_Canarias", "known": False},
    "cantabria": {"code_id": "236", "filename": "236_Codigo_de_Cantabria", "known": False},
    "castilla_la_mancha": {"code_id": "237", "filename": "237_Codigo_de_Castilla-La_Mancha", "known": False},
    "castilla_y_leon": {"code_id": "238", "filename": "238_Codigo_de_Castilla_y_Leon", "known": False},
    "cataluna": {"code_id": "228", "filename": "228_Codigo_de_Cataluna", "known": True},
    "comunidad_valenciana": {"code_id": "230", "filename": "230_Codigo_de_la_Comunidad_Valenciana", "known": True},
    "extremadura": {"code_id": "239", "filename": "239_Codigo_de_Extremadura", "known": False},
    "galicia": {"code_id": "232", "filename": "232_Codigo_de_Galicia", "known": True},
    "madrid": {"code_id": "240", "filename": "240_Codigo_de_la_Comunidad_de_Madrid", "known": False},
    "murcia": {"code_id": "241", "filename": "241_Codigo_de_la_Region_de_Murcia", "known": False},
    "la_rioja": {"code_id": "242", "filename": "242_Codigo_de_La_Rioja", "known": False},
}


def build_code_urls(ccaa_key: str, *, base_url: str = BOE_BASE_URL) -> dict[str, str]:
    """Return the catalog and PDF URLs for a given autonomous community code."""
    spec = DEFAULT_CCAA_CODES[ccaa_key]
    return {
        "catalog": f"{base_url}/codigo.php?id={spec['code_id']}&modo=2",
        "pdf": f"{base_url}/abrir_pdf.php?fich={spec['filename']}.pdf",
    }


_PDF_MAGIC = b"%PDF-"


class BOECCAACrawler(scrapy.Spider):
    """Downloads the consolidated PDF code per régimen común autonomous community.

    For each CCAA in the requested subset (default: all known) the spider
    fetches both the catalog HTML (to grab the last-update date) and the
    PDF. Output layout::

        <folder>/<snapshot_date>/<ccaa_key>/<filename>.pdf
        <folder>/<snapshot_date>/<ccaa_key>/metadata.json
    """

    name = "BOECCAACrawler"
    custom_settings = {
        "DOWNLOAD_DELAY": float(os.environ.get("BOE_DOWNLOAD_DELAY", "1.0")),
        "CONCURRENT_REQUESTS_PER_DOMAIN": 2,
        "USER_AGENT": "hacienda-asesor/0.1 (research; contacto@hacienda-asesor.local)",
    }

    def __init__(
        self,
        folder: str = "./data/html",
        ccaa: str | None = None,
        snapshot_date: str | None = None,
        base_url: str | None = None,
        skip_unknown: bool = False,
        *args: Any,
        **kwargs: Any,
    ) -> None:
        super().__init__(*args, **kwargs)
        snapshot = snapshot_date or datetime.now(UTC).strftime("%Y-%m-%d")
        # Land under the processor's content_dir, namespaced by source:
        # ./data/html/<snapshot>/boe_ccaa/
        self.folder = os.path.join(folder, snapshot, "boe_ccaa")
        self.base_url = (base_url or BOE_BASE_URL).rstrip("/")
        self.skip_unknown = _to_bool(skip_unknown)
        os.makedirs(self.folder, exist_ok=True)
        self._targets = _resolve_targets(ccaa, skip_unknown=self.skip_unknown)

    def start_requests(self) -> Generator[scrapy.Request]:
        for ccaa_key in self._targets:
            urls = build_code_urls(ccaa_key, base_url=self.base_url)
            yield scrapy.Request(
                urls["pdf"],
                callback=self.parse_pdf,
                cb_kwargs={"ccaa_key": ccaa_key, "catalog_url": urls["catalog"]},
                errback=self.handle_error,
                dont_filter=True,
            )

    async def start(self):  # type: ignore[override]
        for ccaa_key in self._targets:
            urls = build_code_urls(ccaa_key, base_url=self.base_url)
            yield scrapy.Request(
                urls["pdf"],
                callback=self.parse_pdf,
                cb_kwargs={"ccaa_key": ccaa_key, "catalog_url": urls["catalog"]},
                errback=self.handle_error,
                dont_filter=True,
            )

    def parse_pdf(self, response: Response, ccaa_key: str, catalog_url: str) -> None:
        if response.status != 200 or not response.body.startswith(_PDF_MAGIC):
            self.logger.warning(
                "Unexpected response for %s: status=%s, first_bytes=%r",
                ccaa_key,
                response.status,
                response.body[:20],
            )
            return
        ccaa_dir = os.path.join(self.folder, ccaa_key)
        os.makedirs(ccaa_dir, exist_ok=True)
        spec = DEFAULT_CCAA_CODES[ccaa_key]
        pdf_path = os.path.join(ccaa_dir, f"{spec['filename']}.pdf")
        with open(pdf_path, "wb") as fh:
            fh.write(response.body)
        metadata = {
            "source_authority": "BOE",
            "source_hierarchy_rank": 7,
            "jurisdiction_scope": f"autonomico:{CCAA_REGIMEN_COMUN[ccaa_key]}",
            "ccaa_key": ccaa_key,
            "ine_code": CCAA_REGIMEN_COMUN[ccaa_key],
            "code_id": spec["code_id"],
            "catalog_url": catalog_url,
            "pdf_url": response.url,
            "pdf_path": pdf_path,
            "pdf_size_bytes": len(response.body),
            "covered_tributos": ["IRPF_autonomico", "ISD", "ITP_AJD"],
            "ingested_at": datetime.now(UTC).isoformat(),
        }
        with open(os.path.join(ccaa_dir, "metadata.json"), "w", encoding="utf-8") as fj:
            json.dump(metadata, fj, ensure_ascii=False, indent=2)

    def handle_error(self, failure: Any) -> None:
        request = failure.request if hasattr(failure, "request") else None
        url = request.url if request else "unknown"
        self.logger.warning("Failed to fetch %s: %s", url, failure)


def _resolve_targets(ccaa: str | None, *, skip_unknown: bool) -> list[str]:
    if ccaa is None or ccaa.lower() in {"all", "todos"}:
        candidates = list(DEFAULT_CCAA_CODES.keys())
    else:
        candidates = [part.strip() for part in re.split(r"[,;]", ccaa) if part.strip()]
    if skip_unknown:
        candidates = [key for key in candidates if DEFAULT_CCAA_CODES[key].get("known")]
    missing = [key for key in candidates if key not in DEFAULT_CCAA_CODES]
    if missing:
        raise ValueError(f"Unknown CCAA keys: {missing}")
    return candidates


def _to_bool(value: object) -> bool:
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in {"1", "true", "yes", "on"}
